### ISSUE TITLE
property `white-space` or a named color mentioned in attribute selector getting replaced.

### ISSUE THREAD

**Issue by xkeshav** [xkeshav/color-collector#6]
initial css file

```css

body { white-space: normal; color: black;}
.link[data-color=white] { color: white}
```

changed after **collect colors** command

```css
/* following :root block added by css color collector */
:root {
	--body__defaultElement--1: white;
	--body__txt--2: black;
}
body { 
	var(--body__defaultElement--1)-space: normal; 
	color:var(--body__txt--2);
}
.link[data-color=var(--body__defaultElement--1)] { 
	color: var(--body__defaultElement--1)
}
```

which is incorrect
